# Segredos para ambiente local (minikube). Não usar em produção.
# Copie de secrets.example.yaml e preencha APP_SECRET se necessário.
apiVersion: v1
kind: Secret
metadata:
  name: lphajir-secrets
  namespace: lphajir
type: Opaque
stringData:
  APP_SECRET: "dev-local-minikube-secret-change-in-prod"
